# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

target 'AlamofireSwiftyJSONDemo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '4.8.2'
  pod 'SwiftyJSON', '5.0.0'
end
