# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

target 'BackendlessVideo' do
  
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Backendless', '5.5.0'

end
