# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'CocoaPodDemo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SCLAlertView', :git => 'https://github.com/vikmeup/SCLAlertView-Swift.git', :branch => '0.8.1'
	
end

