# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SwinjectDemo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Swinject', '~> 1.1.0'
  
end

