# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseChat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

	pod 'Firebase/Core', '6.13.0'
  	pod 'Firebase/Database', '6.13.0'
	pod 'Firebase/Storage', '6.13.0'
	pod 'JSQMessagesViewController'

end
